//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.view;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.TextView;
import cn.com.cml.pets.R.layout;
import cn.com.cml.pets.util.RingtoneUtil_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class VolumeControlFragment_
    extends VolumeControlFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.media_volume_fragment, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        ringtoneUtil = RingtoneUtil_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static VolumeControlFragment_.FragmentBuilder_ builder() {
        return new VolumeControlFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        msgShowView = ((TextView) hasViews.findViewById(cn.com.cml.pets.R.id.msg_show));
        {
            View view = hasViews.findViewById(cn.com.cml.pets.R.id.ring_volume_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VolumeControlFragment_.this.ringValumeControl();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(cn.com.cml.pets.R.id.play_ringtone_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VolumeControlFragment_.this.playRingtone();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(cn.com.cml.pets.R.id.stop_ringtone_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VolumeControlFragment_.this.stopRingtone();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(cn.com.cml.pets.R.id.media_volume_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VolumeControlFragment_.this.mediaValumeControl();
                    }

                }
                );
            }
        }
        initConfig();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public VolumeControlFragment build() {
            VolumeControlFragment_ fragment_ = new VolumeControlFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
