//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.net;

import java.util.ArrayList;
import java.util.Map;
import cn.com.cml.pets.model.RequestModel;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpMethod;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.http.converter.json.GsonHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class PetsApiHelper_
    implements PetsApiHelper
{

    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;
    private String rootUrl;

    public PetsApiHelper_() {
        restTemplate = new RestTemplate();
        rootUrl = "";
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
        restTemplate.getMessageConverters().add(new StringHttpMessageConverter());
        restTemplate.setInterceptors(new ArrayList<ClientHttpRequestInterceptor>());
        restTemplate.getInterceptors().add(new RequestInterceptor());
    }

    @Override
    public RestTemplate getRestTemplate() {
        return restTemplate;
    }

    @Override
    public void setRestTemplate(RestTemplate arg0) {
        this.restTemplate = arg0;
    }

    @Override
    public void setRestErrorHandler(RestErrorHandler arg0) {
        this.restErrorHandler = arg0;
    }

    @Override
    public String index() {
        try {
            return restTemplate.exchange("http://192.168.1.193:8080/Param/index.jsp?name=123456", HttpMethod.GET, null, String.class).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public String indexWithParam(Map<String, String> param) {
        HttpEntity<Map<String, String>> requestEntity = new HttpEntity<Map<String, String>>(param);
        try {
            return restTemplate.exchange("http://192.168.1.193:8080/Param/index.jsp", HttpMethod.POST, requestEntity, String.class).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public String indexWithModel(RequestModel model) {
        HttpEntity<RequestModel> requestEntity = new HttpEntity<RequestModel>(model);
        try {
            return restTemplate.exchange("http://192.168.1.193:8080/Param/index.jsp", HttpMethod.POST, requestEntity, String.class).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
