//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.service;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;

public final class GlobalService_
    extends GlobalService
{


    public static GlobalService_.IntentBuilder_ intent(Context context) {
        return new GlobalService_.IntentBuilder_(context);
    }

    public static GlobalService_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new GlobalService_.IntentBuilder_(fragment);
    }

    public static GlobalService_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new GlobalService_.IntentBuilder_(supportFragment);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, GlobalService_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, GlobalService_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, GlobalService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public GlobalService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
