//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.util;

import android.content.Context;
import android.telephony.TelephonyManager;

public final class DeviceUtil_
    extends DeviceUtil
{

    private Context context_;

    private DeviceUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static DeviceUtil_ getInstance_(Context context) {
        return new DeviceUtil_(context);
    }

    private void init_() {
        phoneManager = ((TelephonyManager) context_.getSystemService(Context.TELEPHONY_SERVICE));
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
