//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.util;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class PrefUtil_
    extends SharedPreferencesHelper
{

    private Context context_;

    public PrefUtil_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
        this.context_ = context;
    }

    public PrefUtil_.PrefUtilEditor_ edit() {
        return new PrefUtil_.PrefUtilEditor_(getSharedPreferences());
    }

    public StringPrefField locationCommand() {
        return stringField("locationCommand", "");
    }

    public IntPrefField locationInterval() {
        return intField("locationInterval", 0);
    }

    public IntPrefField mediaVolume() {
        return intField("mediaVolume", 0);
    }

    public StringPrefField noisyCommand() {
        return stringField("noisyCommand", "");
    }

    public StringPrefField prefix() {
        return stringField("prefix", "");
    }

    public StringPrefField quietCommand() {
        return stringField("quietCommand", "");
    }

    public IntPrefField ringtoneVolume() {
        return intField("ringtoneVolume", 0);
    }

    public StringPrefField simChangeReceiver() {
        return stringField("simChangeReceiver", "");
    }

    public final static class PrefUtilEditor_
        extends EditorHelper<PrefUtil_.PrefUtilEditor_>
    {


        PrefUtilEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<PrefUtil_.PrefUtilEditor_> locationCommand() {
            return stringField("locationCommand");
        }

        public IntPrefEditorField<PrefUtil_.PrefUtilEditor_> locationInterval() {
            return intField("locationInterval");
        }

        public IntPrefEditorField<PrefUtil_.PrefUtilEditor_> mediaVolume() {
            return intField("mediaVolume");
        }

        public StringPrefEditorField<PrefUtil_.PrefUtilEditor_> noisyCommand() {
            return stringField("noisyCommand");
        }

        public StringPrefEditorField<PrefUtil_.PrefUtilEditor_> prefix() {
            return stringField("prefix");
        }

        public StringPrefEditorField<PrefUtil_.PrefUtilEditor_> quietCommand() {
            return stringField("quietCommand");
        }

        public IntPrefEditorField<PrefUtil_.PrefUtilEditor_> ringtoneVolume() {
            return intField("ringtoneVolume");
        }

        public StringPrefEditorField<PrefUtil_.PrefUtilEditor_> simChangeReceiver() {
            return stringField("simChangeReceiver");
        }

    }

}
