//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.util;

import android.content.Context;

public final class RingtoneUtil_
    extends RingtoneUtil
{

    private Context context_;

    private RingtoneUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static RingtoneUtil_ getInstance_(Context context) {
        return new RingtoneUtil_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
