//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package cn.com.cml.pets.util;

import android.content.Context;
import android.media.AudioManager;

public final class VolumeUtil_
    extends VolumeUtil
{

    private Context context_;

    private VolumeUtil_(Context context) {
        context_ = context;
        init_();
    }

    public static VolumeUtil_ getInstance_(Context context) {
        return new VolumeUtil_(context);
    }

    private void init_() {
        audioManager = ((AudioManager) context_.getSystemService(Context.AUDIO_SERVICE));
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
